### ISSUE TITLE
Getting Started Errors Ubuntu 24.04

### ISSUE THREAD

**Issue by MichaelrMentele** [moveit/moveit2_tutorials#935]
### Description

Failing to get through the build step of the moveit2 tutorial https://moveit.picknik.ai/main/doc/tutorials/getting_started/getting_started.html#install-ros-2-and-colcon

### Your environment
* ROS Distro: Jazzy
* OS Version: Ubuntu 24.04
* Source or Binary build? Source, from tutorial
* If binary, which release version?
* If source, which git commit or tag? 
Moveit2: 1d93035fc4fbc2831916bce26d7b03e15b8a86d5
Tutorials: b05445aa9dfe41916e34468a9f14b4058ce868bf

### Steps to reproduce
I'm just following along the tutorial here https://moveit.picknik.ai/main/doc/tutorials/getting_started/getting_started.html#install-ros-2-and-colcon

When I try to `colcon build --mixin release`, I first get errors about catkin_pkg not being found to import. After pip installing catkin `pip install catkin_pkg` (seems like it shouldn't be needed anymore) I get a different error with `moveit_msgs`

I attached my notes stepping thru each step as markdown using warp terminal.

### Expected behaviour
The build should complete successfully. I do recognize I'm on Ubuntu 24.04 and using the latest Ros2 build but it seems worth logging as an issue for those targets. I'll attempt to work around this by using a docker container to work with move it.
[MoveIt Getting Started.md](https://github.com/user-attachments/files/16461692/MoveIt.Getting.Started.md)

### Backtrace or Console output
```
colcon build --mixin release
Starting >>> moveit_resources_panda_description
Starting >>> moveit_common
Starting >>> moveit_msgs
Starting >>> moveit_resources_pr2_description
Starting >>> moveit_configs_utils
Starting >>> moveit_resources_fanuc_description
Starting >>> moveit_resources_prbt_support
Starting >>> gz_ros2_control
Starting >>> robotiq_description
Starting >>> kortex_api
Starting >>> rviz_visual_tools
Starting >>> serial
Starting >>> robotiq_controllers
Finished <<< moveit_common [0.29s]
Finished <<< moveit_resources_panda_description [0.30s]
Finished <<< robotiq_description [0.29s]
Starting >>> rviz_marker_tools
Finished <<< moveit_resources_pr2_description [0.30s]
Starting >>> moveit_resources_panda_moveit_config
Starting >>> dual_arm_panda_moveit_config
Finished <<< kortex_api [0.31s]
Starting >>> kortex_driver
Finished <<< moveit_resources_prbt_support [0.33s]
Finished <<< moveit_resources_fanuc_description [0.34s]
Starting >>> moveit_resources_fanuc_moveit_config
Finished <<< serial [0.35s]
Starting >>> robotiq_driver
Finished <<< robotiq_controllers [0.37s]
Finished <<< moveit_resources_panda_moveit_config [0.13s]
Finished <<< dual_arm_panda_moveit_config [0.14s]
Finished <<< moveit_resources_fanuc_moveit_config [0.12s]
Finished <<< rviz_marker_tools [0.17s]
Starting >>> moveit_resources
Finished <<< kortex_driver [0.16s]
--- stderr: moveit_msgs
CMake Error at /opt/ros/jazzy/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:57 (message):
  execute_process(/home/michael-mentele/miniconda/bin/python3 -m
  rosidl_adapter --package-name moveit_msgs --arguments-file
  /home/michael-mentele/Desktop/trossen-pincher-hello-world/moveit-tutorial-integration-with-robot/build/moveit_msgs/rosidl_adapter__arguments__moveit_msgs.json
  --output-dir
  /home/michael-mentele/Desktop/trossen-pincher-hello-world/moveit-tutorial-integration-with-robot/build/moveit_msgs/rosidl_adapter/moveit_msgs
  --output-file
  /home/michael-mentele/Desktop/trossen-pincher-hello-world/moveit-tutorial-integration-with-robot/build/moveit_msgs/rosidl_adapter/moveit_msgs.idls)
  returned error code 1:

  AttributeError processing template 'msg.idl.em'

  Traceback (most recent call last):

    File "/opt/ros/jazzy/lib/python3.12/site-packages/rosidl_adapter/resource/__init__.py", line 48, in evaluate_template
      _interpreter = em.Interpreter(
                     ^^^^^^^^^^^^^^

  AttributeError: module 'em' has no attribute 'Interpreter'



  During handling of the above exception, another exception occurred:



  Traceback (most recent call last):

    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File "/opt/ros/jazzy/lib/python3.12/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
               ^^^^^^
    File "/opt/ros/jazzy/lib/python3.12/site-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
                     ^^^^^^^^^^^^^^^
    File "/opt/ros/jazzy/lib/python3.12/site-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
      return convert_msg_to_idl(
             ^^^^^^^^^^^^^^^^^^^
    File "/opt/ros/jazzy/lib/python3.12/site-packages/rosidl_adapter/msg/__init__.py", line 39, in convert_msg_to_idl
      expand_template('msg.idl.em', data, output_file, encoding='iso-8859-1')
    File "/opt/ros/jazzy/lib/python3.12/site-packages/rosidl_adapter/resource/__init__.py", line 23, in expand_template
      content = evaluate_template(template_name, data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/ros/jazzy/lib/python3.12/site-packages/rosidl_adapter/resource/__init__.py", line 69, in evaluate_template
      _interpreter.shutdown()
      ^^^^^^^^^^^^^^^^^^^^^

  AttributeError: 'NoneType' object has no attribute 'shutdown'

Call Stack (most recent call first):
  /opt/ros/jazzy/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:132 (rosidl_adapt_interfaces)
  CMakeLists.txt:117 (rosidl_generate_interfaces)


---
Failed   <<< moveit_msgs [0.50s, exited with code 1]
Aborted  <<< rviz_visual_tools [0.49s]
Aborted  <<< robotiq_driver [0.14s]
Aborted  <<< moveit_configs_utils [0.58s]
Aborted  <<< gz_ros2_control [0.71s]
Aborted  <<< moveit_resources [0.41s]

Summary: 14 packages finished [1.08s]
  1 package failed: moveit_msgs
  5 packages aborted: gz_ros2_control moveit_configs_utils moveit_resources robotiq_driver rviz_visual_tools
  2 packages had stderr output: gz_ros2_control moveit_msgs
  52 packages not processed
```

Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.

**Comment by sea-bass** [comment]
This is an issue with the Python packages configured locally on your end -- see e.g. here: https://github.com/ros/genmsg/issues/63

Given you're on Ubuntu 24.04, and if you don't want to use a virtual environment to do pip installs, you could consider trying `sudo apt install ros-dev-tools` as shown here:
https://github.com/ros/genmsg/issues/63

**Comment by MichaelrMentele** [comment]
Thanks for the clue @sea-bass. I'll try rebuilding my virtual env with python.

**Comment by sea-bass** [comment]
I pasted a link wrong in my previous comment. Updated.
